name: hello-world 
on: push 
jobs: 
  my-job: 
    runs-on: ubuntu-latest 
    steps: 
      - name : Get GitHub Pull Request Reviewers
        id : reviews
        uses: LiamPerson/get-reviews-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub-provided token
          GITHUB_REPOSITORY: "kubernetes/kubernetes" # Repo in 'owner/repo' format
          PULL_REQUEST_ID: 127131 
      - name: Print Reviewers JSON File
        run: |
            cat ${{ steps.reviews.outputs.reviews_file_path }}
      # - name: Print File Path
      #   run: |
      #     echo "Reviews JSON file path: ${{ steps.reviews.outputs.reviews_file_path }}"
      # - name: Debug Action Outputs
      #     run: |
      #       echo "Available outputs:"
      #       echo "${{ toJSON(steps.reviews.outputs) }}"        
      # - name: Consume reviews
      #   uses: some/workflow@version
      #   with:
      #     RELEASES_JSON_FILE: ${{ steps.reviews.outputs.reviews_file_path }}