name: hello-world 
on: push 
jobs: 
  my-job: 
    runs-on: ubuntu-latest 
    steps: 
      # - name: my-step
      #   run: echo "Hello World!"
      - name : Get GitHub Pull Request Reviewers
        id : reviews
        uses: LiamPerson/get-reviews-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use GitHub-provided token
          GITHUB_REPOSITORY: "kubernetes/kubernetes" # Repo in 'owner/repo' format
          PULL_REQUEST_ID: 127131 
      - name: Consume reviews
        run: |
          echo "Reviewers file path: ${{ steps.reviews.outputs.reviews_file_path }}"
          cat ${{ steps.reviews.outputs.reviews_file_path }}